name: Get Group ID

on:
  workflow_dispatch:

jobs:
  get-group-id:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot python-dotenv
        
    - name: Create .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        
    - name: Run get_group_id script
      run: python get_group_id.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: get-group-id-logs
        path: "*.log"
